### ISSUE TITLE
*still* does not work, at all

### ISSUE THREAD

**Issue by Merith-TK** [exa-byte/CCTurtleRemoteController#19]
```docker
# Use an official Node.js runtime as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Define the command to run your application
# CMD [ "npm", "start" ]
ENTRYPOINT [ "/app/start.sh"]
```
```bash
#!/bin/bash
npm install
npm run build
npm run build-textures /app/jars/client.jar /app/jars/mods
npm run server
```
```
skynet-bot-1  | npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
skynet-bot-1  | npm warn deprecated vscode-pug-languageservice@0.29.8: WARNING: This project has been renamed to @volar/pug-language-service. Install using @volar/pug-language-service instead.
skynet-bot-1  | npm warn deprecated vscode-typescript-languageservice@0.29.8: WARNING: This project has been renamed to @volar/typescript-language-service. Install using @volar/typescript-language-service instead.
skynet-bot-1  | npm warn deprecated vscode-vue-languageservice@0.29.8: WARNING: This project has been renamed to @volar/vue-language-service. Install using @volar/vue-language-service instead.
skynet-bot-1  | npm error code 1
skynet-bot-1  | npm error path /app/node_modules/canvas
skynet-bot-1  | npm error command failed
skynet-bot-1  | npm error command sh -c node-pre-gyp install --fallback-to-build --update-binary
skynet-bot-1  | npm error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
skynet-bot-1  | npm error node-pre-gyp info it worked if it ends with ok
skynet-bot-1  | npm error node-pre-gyp info using node-pre-gyp@1.0.11
skynet-bot-1  | npm error node-pre-gyp info using node@22.3.0 | linux | x64
skynet-bot-1  | npm error (node:19) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
skynet-bot-1  | npm error (Use `node --trace-deprecation ...` to show where the warning was created)
skynet-bot-1  | npm error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz
skynet-bot-1  | npm error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
skynet-bot-1  | npm error node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.3.0 (node-v127 ABI, glibc) (falling back to source compile with node-gyp) 
skynet-bot-1  | npm error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
skynet-bot-1  | npm error gyp info it worked if it ends with ok
skynet-bot-1  | npm error gyp info using node-gyp@10.1.0
skynet-bot-1  | npm error gyp info using node@22.3.0 | linux | x64
skynet-bot-1  | npm error gyp info ok 
skynet-bot-1  | npm error gyp info it worked if it ends with ok
skynet-bot-1  | npm error gyp info using node-gyp@10.1.0
skynet-bot-1  | npm error gyp info using node@22.3.0 | linux | x64
skynet-bot-1  | npm error gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
skynet-bot-1  | npm error gyp info spawn /usr/bin/python3
skynet-bot-1  | npm error gyp info spawn args [
skynet-bot-1  | npm error gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
skynet-bot-1  | npm error gyp info spawn args 'binding.gyp',
skynet-bot-1  | npm error gyp info spawn args '-f',
skynet-bot-1  | npm error gyp info spawn args 'make',
skynet-bot-1  | npm error gyp info spawn args '-I',
skynet-bot-1  | npm error gyp info spawn args '/app/node_modules/canvas/build/config.gypi',
skynet-bot-1  | npm error gyp info spawn args '-I',
skynet-bot-1  | npm error gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
skynet-bot-1  | npm error gyp info spawn args '-I',
skynet-bot-1  | npm error gyp info spawn args '/root/.cache/node-gyp/22.3.0/include/node/common.gypi',
skynet-bot-1  | npm error gyp info spawn args '-Dlibrary=shared_library',
skynet-bot-1  | npm error gyp info spawn args '-Dvisibility=default',
skynet-bot-1  | npm error gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/22.3.0',
skynet-bot-1  | npm error gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
skynet-bot-1  | npm error gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/22.3.0/<(target_arch)/node.lib',
skynet-bot-1  | npm error gyp info spawn args '-Dmodule_root_dir=/app/node_modules/canvas',
skynet-bot-1  | npm error gyp info spawn args '-Dnode_engine=v8',
skynet-bot-1  | npm error gyp info spawn args '--depth=.',
skynet-bot-1  | npm error gyp info spawn args '--no-parallel',
skynet-bot-1  | npm error gyp info spawn args '--generator-output',
skynet-bot-1  | npm error gyp info spawn args 'build',
skynet-bot-1  | npm error gyp info spawn args '-Goutput_dir=.'
skynet-bot-1  | npm error gyp info spawn args ]
skynet-bot-1  | npm error Package pangocairo was not found in the pkg-config search path.
skynet-bot-1  | npm error Perhaps you should add the directory containing `pangocairo.pc'
skynet-bot-1  | npm error to the PKG_CONFIG_PATH environment variable
skynet-bot-1  | npm error Package 'pangocairo', required by 'virtual:world', not found
skynet-bot-1  | npm error gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
skynet-bot-1  | npm error gyp ERR! configure error 
skynet-bot-1  | npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
skynet-bot-1  | npm error gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:297:18)
skynet-bot-1  | npm error gyp ERR! stack at ChildProcess.emit (node:events:520:28)
skynet-bot-1  | npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
skynet-bot-1  | npm error gyp ERR! System Linux 6.9.3-arch1-1
skynet-bot-1  | npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/app/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
skynet-bot-1  | npm error gyp ERR! cwd /app/node_modules/canvas
skynet-bot-1  | npm error gyp ERR! node -v v22.3.0
skynet-bot-1  | npm error gyp ERR! node-gyp -v v10.1.0
skynet-bot-1  | npm error gyp ERR! not ok 
skynet-bot-1  | npm error node-pre-gyp ERR! build error 
skynet-bot-1  | npm error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
skynet-bot-1  | npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
skynet-bot-1  | npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
skynet-bot-1  | npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
skynet-bot-1  | npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
skynet-bot-1  | npm error node-pre-gyp ERR! System Linux 6.9.3-arch1-1
skynet-bot-1  | npm error node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
skynet-bot-1  | npm error node-pre-gyp ERR! cwd /app/node_modules/canvas
skynet-bot-1  | npm error node-pre-gyp ERR! node -v v22.3.0
skynet-bot-1  | npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
skynet-bot-1  | npm error node-pre-gyp ERR! not ok
skynet-bot-1  | npm error A complete log of this run can be found in: /root/.npm/_logs/2024-06-25T23_03_41_431Z-debug-0.log
skynet-bot-1  | 
skynet-bot-1  | > ccturtleremotecontroller@1.2.0 build
skynet-bot-1  | > vue-tsc --noEmit && vite build
skynet-bot-1  | 
skynet-bot-1  | sh: 1: vue-tsc: not found
skynet-bot-1  | 
skynet-bot-1  | > ccturtleremotecontroller@1.2.0 build-textures
skynet-bot-1  | > node utils/textureExtractor/textureExtractor.js /app/jars/client.jar /app/jars/mods
skynet-bot-1  | 
skynet-bot-1  | node:internal/modules/cjs/loader:1215
skynet-bot-1  |   throw err;
skynet-bot-1  |   ^
skynet-bot-1  | 
skynet-bot-1  | Error: Cannot find module 'unzipper'
skynet-bot-1  | Require stack:
skynet-bot-1  | - /app/utils/textureExtractor/textureExtractor.js
skynet-bot-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
skynet-bot-1  |     at Module._load (node:internal/modules/cjs/loader:1038:27)
skynet-bot-1  |     at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
skynet-bot-1  |     at Module.require (node:internal/modules/cjs/loader:1297:12)
skynet-bot-1  |     at require (node:internal/modules/helpers:123:16)
skynet-bot-1  |     at Object.<anonymous> (/app/utils/textureExtractor/textureExtractor.js:3:18)
skynet-bot-1  |     at Module._compile (node:internal/modules/cjs/loader:1460:14)
skynet-bot-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
skynet-bot-1  |     at Module.load (node:internal/modules/cjs/loader:1275:32)
skynet-bot-1  |     at Module._load (node:internal/modules/cjs/loader:1091:12) {
skynet-bot-1  |   code: 'MODULE_NOT_FOUND',
skynet-bot-1  |   requireStack: [ '/app/utils/textureExtractor/textureExtractor.js' ]
skynet-bot-1  | }
skynet-bot-1  | 
skynet-bot-1  | Node.js v22.3.0
skynet-bot-1  | 
skynet-bot-1  | > ccturtleremotecontroller@1.2.0 server
skynet-bot-1  | > node src/server/server.js
skynet-bot-1  | 
skynet-bot-1  | node:internal/modules/cjs/loader:1215
skynet-bot-1  |   throw err;
skynet-bot-1  |   ^
skynet-bot-1  | 
skynet-bot-1  | Error: Cannot find module 'express'
skynet-bot-1  | Require stack:
skynet-bot-1  | - /app/src/server/server.js
skynet-bot-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
skynet-bot-1  |     at Module._load (node:internal/modules/cjs/loader:1038:27)
skynet-bot-1  |     at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
skynet-bot-1  |     at Module.require (node:internal/modules/cjs/loader:1297:12)
skynet-bot-1  |     at require (node:internal/modules/helpers:123:16)
skynet-bot-1  |     at Object.<anonymous> (/app/src/server/server.js:1:17)
skynet-bot-1  |     at Module._compile (node:internal/modules/cjs/loader:1460:14)
skynet-bot-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
skynet-bot-1  |     at Module.load (node:internal/modules/cjs/loader:1275:32)
skynet-bot-1  |     at Module._load (node:internal/modules/cjs/loader:1091:12) {
skynet-bot-1  |   code: 'MODULE_NOT_FOUND',
skynet-bot-1  |   requireStack: [ '/app/src/server/server.js' ]
skynet-bot-1  | }
skynet-bot-1  | 
skynet-bot-1  | Node.js v22.3.0
skynet-bot-1 exited with code 1
```

**Comment by exa-byte** [comment]
Its not really an issue of the script, you're not installing the dev dependencies in the docker file. I assume the official node image sets node env to production which causes it to only install default dependencies. Try either setting the node env back to sth else or find another way to run npm install that also installs dev dependencies.

**Comment by saerio** [comment]
`apt update && apt install -y build-essential libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev pkg-config`
will fix your issue
